### ISSUE TITLE
Job request design

### ISSUE THREAD

**Issue by schneefux** [vainglorygame/joblib#2]
#1
 
---
vainglorygame/apigrabber/issues/36 Web or a cli tool needs to insert into jobs:
  * priority `0`
  * status `"open"`
  * type `"grab"`
  * payload:
```json
{
  "region": "eu",
  "params": {
    "filter[playerNames]": ["shutterfly"],
    "filter[createdAt-start]": "2017-02-12T00:00:00Z",
    "filter[createdAt-start]": "2017-02-19T00:00:00Z"
  }
}
```
---
vainglorygame/processor/issues/20 Apigrabber will insert a job for Processor:
  * priority (same)
  * status `"open"`
  * type `"process"`
  * payload:
```json
{ "id": "xxxx-xxxx-xxxxx" }
```

**Comment by kvahuja** [comment]
will plug this into home page for player serch..

**Comment by kvahuja** [comment]
review https://github.com/vainglorygame/vainsocial/pull/9.

**Comment by schneefux** [comment]
For practical reasons, changing the process job payload from `{"id": "xxx"}` to `{"id": "xxx", "type": "match"}`.

**Comment by schneefux** [comment]
done
